Document upload
MikenasIgnas/DLC-Journal-BackEnd pull request #16
Opened 2024-02-16 17:36 UTC by MikenasIgnas

2024-02-17 09:24 UTC, NorbertasM requested changes

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/allCollocationsCsvController.ts
> +import RackSchema from '../shemas/RackSchema'
Lygiavimas ir rykiavimas

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/allCollocationsCsvController.ts
> +    console.error(error)
delete

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/deleteDocument.ts
> +  file: {uid: number, name: string, status: string}
{ uid: number, ...string }

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/deleteDocument.ts
> +    console.error(error)
delete

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/deleteDocument.ts
Kitas merge requestas vadinasi document count, nors ten kaip supratau ne apie dokumentų failus. Dabar čia užklausa deleteDocument, bet šį kartą dokumentas jau pdf ir jis priklauso įmonei. Ir merge requesto ir užklausos pavadinimai turi būti pakeisti, kad būtų aišku apie kokį dokumentą kalbama

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/deleteDocument.ts
> +    const company = await CompanySchema.findById({_id: id})
{ _id: id }

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/getDocument.ts
Tas pats kas ir anoj užklausoj. Ar ši užklausa veikia?

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/uploadDocument.ts
Tas pats kas ir kitom dokumentų užklausom

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/companyControllers/uploadDocument.ts
> +        },
viena eilutė

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/singleCollocationCsvController.ts
> +import RackSchema from '../shemas/RackSchema'
Lygiavimas

2024-02-17 09:24 UTC, NorbertasM commented on src/controllers/singleCollocationCsvController.ts
> +    console.error(error)
delete

2024-02-17 09:24 UTC, NorbertasM commented on src/routes/companyRoutes.ts
> +router.get('/document', verifyToken, verifyAdmin, upload.single('file'), getDocument)
Kaip suprast tą parsisiuntimą? Paduodi failą kurį nori parsisųst ir jį parsisiunti?

2024-02-17 09:24 UTC, NorbertasM commented on src/shemas/CompanySchema.ts
> +  document:    [{type: String, required: false}],
Tarpai

2024-02-17 11:04 UTC, MikenasIgnas commented on src/controllers/allCollocationsCsvController.ts
> +import RackSchema from '../shemas/RackSchema'
done

2024-02-17 11:05 UTC, MikenasIgnas commented on src/controllers/companyControllers/deleteDocument.ts
> +  file: {uid: number, name: string, status: string}
done

2024-02-17 11:05 UTC, MikenasIgnas commented on src/controllers/allCollocationsCsvController.ts
> +    console.error(error)
done

2024-02-17 11:06 UTC, MikenasIgnas commented on src/controllers/companyControllers/deleteDocument.ts
> +    console.error(error)
done

2024-02-17 11:06 UTC, MikenasIgnas commented on src/controllers/companyControllers/deleteDocument.ts
> +    const company = await CompanySchema.findById({_id: id})
done

2024-02-17 11:07 UTC, MikenasIgnas commented on src/controllers/companyControllers/uploadDocument.ts
> +        },
done

2024-02-17 11:08 UTC, MikenasIgnas commented on src/controllers/singleCollocationCsvController.ts
> +import RackSchema from '../shemas/RackSchema'
done

2024-02-17 11:08 UTC, MikenasIgnas commented on src/controllers/singleCollocationCsvController.ts
> +    console.error(error)
done

2024-02-17 11:09 UTC, MikenasIgnas commented on src/routes/companyRoutes.ts
> +router.get('/document', verifyToken, verifyAdmin, upload.single('file'), getDocument)
done

2024-02-17 11:10 UTC, MikenasIgnas commented on src/shemas/CompanySchema.ts
> +  document:    [{type: String, required: false}],
done

2024-02-20 17:50 UTC, NorbertasM approved these changes

2024-02-20 17:50 UTC, merged